# Configuración general del proyecto
app:
  title: "Analítica de Datos"
  debug: true
paths:
  data_raw: "data/raw"
  data_interim: "data/interim"
  data_processed: "data/processed"
  data_external: "data/external"
logging:
  level: "INFO"
scraping:
  user_agent: "Mozilla/5.0 (compatible; ProyectoAnalitica/1.0)"
  timeout_seconds: 10
